/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#0EA5E9',
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
          400: '#38BDF8',
          500: '#0EA5E9',
          600: '#0284C7',
          700: '#0369A1',
          800: '#075985',
          900: '#0C4A6E',
        },
        secondary: {
          DEFAULT: '#1E3A5F',
          50: '#E8EDF4',
          100: '#D1DBE9',
          200: '#A3B7D3',
          300: '#7593BD',
          400: '#476FA7',
          500: '#1E3A5F',
          600: '#182E4C',
          700: '#122339',
          800: '#0C1726',
          900: '#060C13',
        },
        accent: {
          DEFAULT: '#F59E0B',
          50: '#FEF3E2',
          100: '#FDE8C5',
          200: '#FBD18B',
          300: '#F9BA51',
          400: '#F7A317',
          500: '#F59E0B',
          600: '#C47E09',
          700: '#935F07',
          800: '#623F04',
          900: '#312002',
        },
        // AuSuivant France landing page palette
        fr: {
          navy: '#0F172A',
          'navy-800': '#1E293B',
          'navy-700': '#334155',
          cream: '#FAFAF8',
          'cream-warm': '#F5F0E8',
          gold: '#D4A853',
          'gold-light': '#E8D5A8',
          'gold-pale': '#FDF8ED',
        },
        // BleSaf receptionist dashboard palette
        bs: {
          bg: '#F6F5F0',
          surface: '#FFFFFF',
          'surface-alt': '#F0EFEA',
          border: '#E8E6DF',
          'text-primary': '#1A1A1A',
          'text-secondary': '#6B6960',
          'text-tertiary': '#9E9B90',
          accent: '#0F7B6C',
          'accent-light': '#E8F5F1',
          'accent-dark': '#0A5C50',
          red: '#D94F3B',
          'red-light': '#FDF0ED',
          amber: '#D4920B',
          'amber-light': '#FEF7E6',
          green: '#2D8B4E',
          'green-light': '#EDF7F0',
          blue: '#3B7DD9',
          'blue-light': '#EDF3FC',
        },
        // Teal Clinical — admin dashboard palette (legacy)
        admin: {
          DEFAULT: '#267B75',
          text: '#132E2C',
          secondary: '#4E7572',
          muted: '#8AADAA',
          bg: '#FDFFFF',
          subtle: '#F3FAF9',
          border: '#D0E8E5',
          'border-light': '#E6F2F0',
          accent: '#267B75',
          'accent-hover': '#1F6560',
          'accent-light': '#DAF5E0',
          positive: '#337023',
          negative: '#E15720',
          chart: '#459FB8',
        },
        // Admin redesign — brand tokens
        brand: {
          DEFAULT: '#1C4A3B',
          mid:    '#2D6B55',
          light:  '#3D8A6E',
          pale:   '#E8F2EE',
          pale2:  '#D4E9E0',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          2: '#F0EFEB',
        },
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'system-ui', 'sans-serif'],
        arabic: ['IBM Plex Sans Arabic', 'system-ui', 'sans-serif'],
        outfit: ['Outfit', 'system-ui', 'sans-serif'],
        playfair: ['Playfair Display', 'Georgia', 'serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
        dm: ['DM Sans', 'system-ui', 'sans-serif'],
        'dm-mono': ['DM Mono', 'monospace'],
        fraunces: ['Fraunces', 'Georgia', 'serif'],
        'dm-serif': ['DM Serif Display', 'Georgia', 'serif'],
      },
      // BleSaf receptionist dashboard tokens
      boxShadow: {
        'bs-sm': '0 1px 2px rgba(0,0,0,0.04)',
        'bs-md': '0 4px 12px rgba(0,0,0,0.06)',
        'bs-lg': '0 8px 32px rgba(0,0,0,0.10)',
        'bs-float': '0 6px 24px rgba(15,123,108,0.25)',
        'bs-sheet': '0 -4px 32px rgba(0,0,0,0.12)',
      },
      borderRadius: {
        'bs': '12px',
        'bs-sm': '8px',
        'bs-xs': '6px',
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideInDown: {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'bs-slide-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'bs-pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.3' },
        },
        'bs-pulse-cta': {
          '0%, 100%': { opacity: '0' },
          '50%': { opacity: '1' },
        },
        'pulse-ring': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(176,122,28,0.3)' },
          '50%':       { boxShadow: '0 0 0 4px rgba(176,122,28,0)' },
        },
        'menu-pop': {
          '0%':   { opacity: '0', transform: 'scale(0.95) translateY(-4px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'dropdown-in': {
          from: { opacity: '0', transform: 'translateY(-8px) scale(0.98)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'ob-card-in': {
          from: { opacity: '0', transform: 'translateY(18px) scale(0.98)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'ob-pulse-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)', boxShadow: '0 0 0 0 rgba(27,107,69,0.4)' },
          '50%':      { opacity: '0.6', transform: 'scale(1.25)', boxShadow: '0 0 0 5px rgba(27,107,69,0)' },
        },
        'ob-toast-pop': {
          from: { opacity: '0', transform: 'scale(0.7) translateY(-6px)' },
          to:   { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'ob-screen-in': {
          from: { opacity: '0', transform: 'translateY(20px) scale(0.97)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 300ms ease-out both',
        'slide-in-down': 'slideInDown 200ms ease-out both',
        'bs-slide-in': 'bs-slide-in 0.4s ease-out both',
        'bs-pulse-dot': 'bs-pulse-dot 1.5s ease infinite',
        'bs-pulse-cta': 'bs-pulse-cta 3s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 2s ease-in-out infinite',
        'menu-pop': 'menu-pop 0.12s cubic-bezier(0.22, 1, 0.36, 1)',
        'dropdown-in': 'dropdown-in 0.18s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'ob-card-in': 'ob-card-in 0.45s cubic-bezier(0.22, 1, 0.36, 1) both',
        'ob-pulse-dot': 'ob-pulse-dot 1.9s ease infinite',
        'ob-toast-pop': 'ob-toast-pop 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) 0.3s both',
        'ob-screen-in': 'ob-screen-in 0.45s cubic-bezier(0.22, 1, 0.36, 1) both',
      },
    },
  },
  plugins: [],
}
