import { useCallback } from 'react';
import { useNavigate, Navigate } from 'react-router-dom';
import { useOnboardingStore } from '../stores/onboardingStore';
import { useAuthStore } from '../stores/authStore';
import { api } from '../lib/api';
import { downloadQrCodePdf } from '../utils/qrCodePdf';
import ProgressBar from '../components/onboarding/ProgressBar';
import QRCodeDisplay from '../components/onboarding/QRCodeDisplay';
import PatientSimulation from '../components/onboarding/PatientSimulation';

export default function WelcomePage() {
  const navigate = useNavigate();
  const { clinicName: onboardingName, clinicId: onboardingClinicId, qrCodeDataUrl, qrCodeUrl, setSimulationComplete } = useOnboardingStore();
  const checkAuth = useAuthStore((s) => s.checkAuth);
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const authClinic = useAuthStore((s) => s.clinic);

  // Fall back to auth store for clinic data (survives page refresh)
  const clinicId = onboardingClinicId || authClinic?.id || null;
  const clinicName = onboardingName || authClinic?.name || '';

  // Guard: must have QR code data (generated by SetupPage)
  if (!isAuthenticated || !clinicId || !qrCodeDataUrl || !qrCodeUrl) {
    // If authenticated but missing QR data, send through setup to regenerate it
    if (isAuthenticated && clinicId) {
      return <Navigate to="/signup/setup" replace />;
    }
    return <Navigate to="/signup" replace />;
  }

  const handleDownloadPdf = useCallback(async () => {
    await downloadQrCodePdf(qrCodeDataUrl, clinicName);
    // Mark QR downloaded in activation checklist
    try {
      await api.updateActivationProgress({ qrDownloaded: true });
    } catch { /* ignore */ }
  }, [qrCodeDataUrl, clinicName]);

  const handleGoToDashboard = useCallback(async () => {
    // Mark onboarding as complete
    try {
      await api.updateOnboarding(3, true);
    } catch { /* ignore */ }

    // Refresh auth state so dashboard knows onboarding is done
    await checkAuth();

    navigate('/dashboard', { replace: true });
  }, [checkAuth, navigate]);

  return (
    <div className="min-h-screen flex flex-col" style={{ backgroundColor: '#F4F7F5' }}>
      <ProgressBar currentStep={3} />

      <main className="flex-1 flex items-center justify-center px-4 py-8 pt-8">
        <div className="w-full" style={{ maxWidth: '960px' }}>
          {/* Two-panel layout (desktop side-by-side, mobile stacked) */}
          <div className="flex flex-col lg:flex-row gap-8 lg:gap-12 items-start justify-center">
            {/* Left panel — QR Code */}
            <div
              className="w-full lg:w-auto bg-white rounded-xl p-8 shadow-sm flex flex-col items-center"
              style={{ borderRadius: '12px', maxWidth: '420px', margin: '0 auto' }}
            >
              <h2 className="text-xl font-bold mb-6 text-center" style={{ color: '#1A1A2E', fontSize: '22px' }}>
                Votre QR Code est prêt.
              </h2>

              <QRCodeDisplay
                url={qrCodeUrl}
                clinicName={clinicName}
                size={220}
              />

              {/* Buttons */}
              <div className="w-full mt-8 space-y-3">
                {/* Primary — Download PDF */}
                <button
                  onClick={handleDownloadPdf}
                  className="w-full font-semibold text-white flex items-center justify-center gap-2"
                  style={{
                    height: '48px',
                    borderRadius: '8px',
                    backgroundColor: '#1B7A4A',
                    fontSize: '15px',
                    fontWeight: 600,
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#165f3a')}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = '#1B7A4A')}
                >
                  Télécharger mon QR code (PDF)
                </button>

                {/* Secondary — Go to dashboard */}
                <button
                  onClick={handleGoToDashboard}
                  className="w-full font-semibold flex items-center justify-center gap-2"
                  style={{
                    height: '48px',
                    borderRadius: '8px',
                    border: '2px solid #1B7A4A',
                    color: '#1B7A4A',
                    backgroundColor: 'transparent',
                    fontSize: '15px',
                    fontWeight: 600,
                  }}
                >
                  Aller au tableau de bord →
                </button>
              </div>
            </div>

            {/* Right panel — Simulation */}
            <div
              className="w-full lg:w-auto flex flex-col items-center"
              style={{ maxWidth: '420px', margin: '0 auto' }}
            >
              <PatientSimulation onComplete={setSimulationComplete} />
            </div>
          </div>
        </div>
      </main>

      {/* Responsive overrides for mobile QR size */}
      <style>{`
        @media (max-width: 768px) {
          .qr-mobile-override svg {
            width: 180px !important;
            height: 180px !important;
          }
        }
      `}</style>
    </div>
  );
}
